import "./globals.css"

import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Link from "next/link"
import { ClerkProvider } from "@clerk/nextjs"

import Header from "@/components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className} suppressHydrationWarning={true}>
          <main className="flex min-h-screen flex-col items-center gap-8 p-24">
            <Header />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  )
}
